### ISSUE TITLE
Sample Fails to Compile on WSL Unbuntu

### ISSUE THREAD

**Issue by mwasplund** [zerodaycode/Zork#48]
### Description
Fails to compile sample calculator on WSL Ubuntu 22.04

### Steps to reproduce

1. Download latest release of zork++
2. Unzip tarball and add to path
3. run ```zork++ new calculator --compiler clang```

### Expected result
Sample is created and built.

### Actual result
Compiler error with missing "import std"

mwasplund@MWASPLUND-XPS15:~/repos/test-zork$ ~/zork/dist/zork++ new calculator --compiler clang

[INFO]: Starting a new C++ compilation job with Zork on [Linux 5.10.102.1-microsoft-standard-WSL2, 64bit, ELF]
main.cpp:1:8: fatal error: module 'std' not found
import std;
~~~~~~~^~~
1 error generated.


### Possible solution
I assume the default clang is too old to have std header unit. Will investigate if updating fixes, but figured this bug should include a min version for clang++ before getting started.

### Environment
OS: WSL Unbuntu 22.04
Stack used and version: clang 
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by Pyzyryab** [comment]
Hello @mwasplund ! Thanks for your feedback.

Clang 14 doesn't fully support import translations from include directives.
We only make it work having at least the 15.0.1 (that's what I remeber).

The key thing it's that the autogenerated example is just an example. We aren't sure if we must constraint compiler version, because is (from our perspective) a third party tool (but we do with the modules min required version).

Let us know please if upgrading your compiler version things work.

**Comment by Pyzyryab** [comment]
We are closing this issue, since isn't being updated
